In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [5]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print('Vectorized version: ' + str(1000*(toc-tic)) + ' ms')

249819.18333802797
Vectorized version: 0.8819103240966797 ms


In [6]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print('For loop version: ' + str(1000*(toc-tic)) + ' ms')

249819.18333802116
For loop version: 643.017053604126 ms


In [8]:
v = [1, 2, 3, 4, 5, 6, 7]
expp = np.exp(v)
expp

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ,  403.42879349, 1096.63315843])

In [9]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [10]:
test = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12
                                             ]])

In [11]:
test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
ss = test.sum(axis=0)

In [13]:
ss

array([15, 18, 21, 24])

In [14]:
percentage = 100 * test/ss.reshape(1, 4)

In [15]:
percentage

array([[ 6.66666667, 11.11111111, 14.28571429, 16.66666667],
       [33.33333333, 33.33333333, 33.33333333, 33.33333333],
       [60.        , 55.55555556, 52.38095238, 50.        ]])